### ISSUE TITLE
404 Errors with store.ui.com redesign 

### ISSUE THREAD

**Issue by JacobErnst98** [EvotecIT/UnifiStockTracker#2]
Unable to get https://store.ui.com/collections/unifi-door-access/products.json. Error: The remote server returned an error: (404) Not Found.
I'm seeing 404 errors when running get-unifistock -store USA and wait-unifistock -store USA
Thinking this is due to the redesign.

**Comment by PrzemyslawKlys** [comment]
Right, I can see the same thing on EU store after redesign. The question is if products.json is still available but in different place or they removed it comepletely.

**Comment by jazuntee** [comment]
I don't think products.json is still there. But it looks like you might be able to use the new API to get the same data. I just based this off requests I saw the new site make. There is a search option to filter the list down as well.

```PowerShell
$Products = Invoke-RestMethod -UseBasicParsing -Uri "https://ecomm.svc.ui.com/graphql" -Method Post -ContentType "application/json" -Body "{`"operationName`":`"GetProductsForLandingPagePro`",`"variables`":{`"input`":{`"limit`":125,`"offset`":0,`"filter`":{`"storeId`":`"us`",`"language`":`"en`",`"line`":`"Unifi`"}}},`"query`":`"query GetProductsForLandingPagePro(`$input: StorefrontProductListInput!) {\n  storefrontProducts(input: `$input) {\n    pagination {\n      limit\n      offset\n      total\n      __typename\n    }\n    items {\n      ...LandingProProductFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment LandingProProductFragment on StorefrontProduct {\n  id\n  title\n  shortTitle\n  name\n  slug\n  collectionSlug\n  organizationalCollectionSlug\n  shortDescription\n  tags {\n    name\n    __typename\n  }\n  gallery {\n    ...ImageOnlyGalleryFragment\n    __typename\n  }\n  options {\n    id\n    title\n    values {\n      id\n      title\n      __typename\n    }\n    __typename\n  }\n  variants {\n    id\n    sku\n    status\n    title\n    galleryItemIds\n    isEarlyAccess\n    optionValueIds\n    displayPrice {\n      ...MoneyFragment\n      __typename\n    }\n    hasPurchaseHistory\n    __typename\n  }\n  __typename\n}\n\nfragment ImageOnlyGalleryFragment on Gallery {\n  id\n  items {\n    id\n    data {\n      __typename\n      ... on Asset {\n        id\n        mimeType\n        url\n        height\n        width\n        __typename\n      }\n    }\n    __typename\n  }\n  type\n  __typename\n}\n\nfragment MoneyFragment on Money {\n  amount\n  currency\n  __typename\n}`"}"
```

**Comment by PrzemyslawKlys** [comment]
Nice find. Thank you. It seems to return 125 for US. I'll try to convert it to so it works

**Comment by PrzemyslawKlys** [comment]
## Usage

Due to Unifi store changes this module now contains 4 commands:

- `Get-UnifiStock` - supporting only US/EU stores
- `Get-UnifiStockLegacy` - supporting all other stores
- `Wait-UnifiStock` - supporting only US/EU stores
- `Wait-UnifiStockLegacy` - supporting all other stores

Once redesign for all stores will be done I'll try to fix other stores and remove compatibility with old ones.

### Getting a list of products (non-EU, non-USA) stores

Get all products from 3 categories in Brazil store, sort them by name and display

```powershell
Get-UnifiStockLegacy -Store Brazil -Collection Protect, ProtectAccessories, ProtectNVR | Sort-Object -Property Name | Format-Table
```

Get all products from 2 categories in Brazil store, sort them by name and display

```powershell
Get-UnifiStockLegacy -Store Brazil -Collection Protect, NetworkWifi | Sort-Object -Property Name | Format-Table
```

Get all products from India store, sort them by name and display

```powershell
Get-UnifiStockLegacy -Store India | Sort-Object -Property Name | Format-Table
```

### Waiting for specific products (non-EU, non-USA)

Wait for 4 products of which one will be ignored because it doesn't exists and recheck store every 60 seconds (Europe store is default)

```powershell
Wait-UnifiStockLegacy -ProductName 'UniFi6 Mesh', 'G4 Doorbell Pro', 'Camera G4 Pro', 'Test' -Seconds 60
```

Wait for 1 product via specific SKU and recheck store every 60 seconds (Europe store is default)

```powershell
Wait-UnifiStockLegacy -ProductSKU 'UDR-EU' -ProductName 'Switch Flex XG' -Seconds 60
```

### Getting a list of products (EU, USA) stores

```powershell
Get-UnifiStock -Store Europe | Sort-Object -Property Name | Format-Table
Get-UnifiStock -Store USA -Verbose | Sort-Object -Property Name | Format-Table

Get-UnifiStock -Store USA -Collection AccessoriesCabling, CableBox | Sort-Object -Property Name | Format-Table
Get-UnifiStock -Store Europe -Collection CameraSecurityDome360, CameraSecurityCompactPoEWired | Sort-Object -Property Name | Format-Table
Get-UnifiStock -Store USA -Collection HostingAndGatewaysCloud,DreamMachine, DreamRouter | Sort-Object -Property Name | Format-Table
```

### Waiting for specific products (EU, USA)

```powershell
Wait-UnifiStock -ProductName 'UniFi6 Mesh', 'G4 Doorbell Pro', 'Camera G4 Pro', 'Test' -Seconds 60 -Store USA
Wait-UnifiStock -ProductSKU 'UDR-EU' -ProductName 'Switch Flex XG' -Seconds 60 -Store Europe
Wait-UnifiStock -ProductName 'Access Point AC Lite' -Seconds 60 -Store Europe
```

Version 2.0.0 is out. Give it a try, but seems to work. Thank you @jasoth
